### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 

### ISSUE THREAD

**Issue by unintended-consequences** [KBlixt/Movie-Extra-Downloader#8]
I have been running with -l to pull trailers for my library. Most movies work fine. Some movies cause the script to end prematurely, with the following output:

Traceback (most recent call last):
File "Movie-Extra-Downloader.py", line 165, in
handle_library(args.library)
File "Movie-Extra-Downloader.py", line 140, in handle_library
handle_directory(os.path.join(library, folder))
File "Movie-Extra-Downloader.py", line 101, in handle_directory
download_extra(directory, extra_config, tmp_folder)
File "/home/trailer/Movie-Extra-Downloader/main.py", line 129, in download_extra
process_trailers_config(tmp_folder)
File "/home/trailer/Movie-Extra-Downloader/main.py", line 11, in process_trailers_config
finder.search()
File "/home/trailer/Movie-Extra-Downloader/extra_finder.py", line 113, in search
video = create_youtube_video()
File "/home/trailer/Movie-Extra-Downloader/extra_finder.py", line 62, in create_youtube_video
youtube_video['average_rating'] * (1 - 1 / ((youtube_video['view_count'] / 60) ** 0.5))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by unintended-consequences** [comment]
I have been running with -l to pull trailers for my library. Most movies work fine. Some movies cause the script to end prematurely, with the following output:

`Traceback (most recent call last):
  File "Movie-Extra-Downloader.py", line 165, in <module>
    handle_library(args.library)
  File "Movie-Extra-Downloader.py", line 140, in handle_library
    handle_directory(os.path.join(library, folder))
  File "Movie-Extra-Downloader.py", line 101, in handle_directory
    download_extra(directory, extra_config, tmp_folder)
  File "/home/andrew/trailer/Movie-Extra-Downloader/main.py", line 129, in download_extra
    process_trailers_config(tmp_folder)
  File "/home/andrew/trailer/Movie-Extra-Downloader/main.py", line 11, in process_trailers_config
    finder.search()
  File "/home/andrew/trailer/Movie-Extra-Downloader/extra_finder.py", line 113, in search
    video = create_youtube_video()
  File "/home/andrew/trailer/Movie-Extra-Downloader/extra_finder.py", line 62, in create_youtube_video
    youtube_video['average_rating'] * (1 - 1 / ((youtube_video['view_count'] / 60) ** 0.5))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
'

**Comment by unintended-consequences** [comment]
Have never used Github or python, but i identified the problem:

youtube_video['average_rating'] can return None if the video is unrated, which causes the TypeError - you can't do math on a NoneType. 

So you need another error trap at Line 60

"if youtube_video['average_rating'] is None:
youtube_video['average_rating'] = 4

No science behind 4, most videos rated 4.5 and higher.

**Comment by KBlixt** [comment]
Excellent, thanks for finding this. I'll be taking a look into this this weekend.

**Comment by KBlixt** [comment]
This should be in order now.
